# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Birkengym"

[social.params]
icon = "brand-github"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/birkengym/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@birkengy"

[social.params]
icon = "brand-youtube"